version: "3.7"

services: 
  ruspie-api:
    build:
      context: ./ruspie
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./ruspie
        target: /app
    networks:
      - ruspie 
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - ./volumes/minio/data:/export
      - ./volumes/minio/config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=miniokey
      - MINIO_SECRET_KEY=miniosecret
    command: server -console-address :9002 /export
    networks:
      - ruspie
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    networks:
      - ruspie
    entrypoint: >
      /bin/sh -c " apk add --no-cache bash; wait-for-it.sh minio:9000 -- echo 'Minio is up. Creating the bucket!!'; /usr/bin/mc config host add myminio http://minio:9000 miniokey miniosecret; /usr/bin/mc mb myminio/ruspie; /usr/bin/mc policy set download myminio/ruspie; exit 0; "
  ruspie-web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
    - type: bind
      source: ./web
      target: /app
    - type: bind
      source: ./web/node_modules
      target: /app/node_modules
    environment: 
      - REACT_APP_RUSPIE_API_URL=http://ruspie-api:8080
      - WDS_SOCKET_HOST=127.0.0.1 
    networks:
      - ruspie
networks:
  ruspie:
