version: "3.7"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - ./volumes/minio/data:/export
      - ./volumes/minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=miniokey
      - MINIO_ROOT_PASSWORD=miniosecret
    command: server -console-address :9002 /export
    networks:
      - ruspie

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    networks:
      - ruspie
    entrypoint: >
      /bin/sh -c " apk add --no-cache bash; wait-for-it.sh minio:9000 -- echo 'Minio is up. Creating the bucket!!'; /usr/bin/mc config host add myminio http://minio:9000 miniokey miniosecret; /usr/bin/mc mb myminio/ruspie; /usr/bin/mc policy set download myminio/ruspie; exit 0; "

  ruspie-web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    environment:
      - REACT_APP_RUSPIE_API_URL=http://ruspie-api:8080
      - WDS_SOCKET_HOST=127.0.0.1
    networks:
      - ruspie

  ruspie-api:
    build:
      context: ./ruspie
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SOURCE=S3
      - DEFAULT_EXT=parquet
      - AWS_SECRET_ACCESS_KEY=miniosecret
      - AWS_ACCESS_KEY_ID=miniokey
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://minio:9000
      - PRE_FETCH_ENABLED=true
      - PRE_FETCH_INTERVAL=60
      - MONGO_URI=mongodb://mongo:mongo@mongodb:27017
    networks:
      - ruspie
    depends_on:
      - minio
      - mongodb

  robinpie-api:
    build:
      context: ./robinpie/
      dockerfile: Dockerfile
    environment:
      - AWS_SECRET_ACCESS_KEY=miniosecret
      - AWS_ACCESS_KEY_ID=miniokey
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://minio:9000
      - PRE_FETCH_INTERVAL=30
      - RUSPIE_URL=http://ruspie-api:8080
      - MONGO_URI=mongodb://mongo:mongo@mongodb:27017
    networks:
      - ruspie
    depends_on:
      - minio
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongo-data:/data/db
    networks:
      - ruspie

networks:
  ruspie:
