[package]
name = "ruspie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# roapi = {git = "https://github.com/roapi/roapi"}
# columnq = {git = "https://github.com/roapi/roapi"}
roapi = {path = "../roapi"}
columnq = {path = "../columnq"}
anyhow = "1.0.64"
tokio = { version = "1", features = ["rt-multi-thread"] }
axum = { version = "0.5", features = ["default", "http2"] }
serde_json = "1.0.86"
tower-http="0"
dotenv="0"
config="0"